### ISSUE TITLE
When i use gyp to generate a makefile, i get an error message: Undefined variable library in projecct.gyp

### ISSUE THREAD

**Issue by xuxiaofei0618** [tghosgor/postgrespp#1]
I'm sure that i installed all librarys required in project.gyp. e.g. libpq.so, libboost_system.so, libboost_log.so, libboost_log_setup.so.
gcc version is 7.3.1 20180312 (GCC) which support c++14 built-in.
boost version is 1.66.0.
linux version is archlinux 4.15.15-1-ARCH.
Could you give me a help? Thanks very much.

**Comment by tghosgor** [comment]
I forgot about gyp at all.

Did some research now, apparently that pattern was used for specifying shared/static libraries at generation time.

You should add `-Dlibrary=static_library` or `-Dlibrary=shared_library` to 'gyp' command while generating the makefiles.

**Comment by xuxiaofei0618** [comment]
Thanks very very much.

Finally solve the problem by adding -Dlibrary=shared_library to 'gyp' command: gyp --depth=. -Dlibrary=shared_library project.gyp
