### ISSUE TITLE
Arrays 

### ISSUE THREAD

**Issue by lacasaprivata2** [tghosgor/postgrespp#5]
Does this library support binding arrays to a query param? This will be the primary reason for me to switch over from Rust which has been hell on productivity

**Comment by tghosgor** [comment]
I don't think so. You can try to specialize type encoder/decoder (as in [here](https://github.com/tghosgor/postgrespp/blob/f11d01d79689a5942e7785957f48d6fb564528e9/include/builtin_type_encoders.hpp)). Maybe I can try adding it when I have free time.

**Comment by lacasaprivata2** [comment]
thank you - that would be great since it also handles bulk inserts if one follows the approach:

INSERT INTO ..... SELECT* FROM UNNEST ( )
