### ISSUE TITLE
could not deconde numeric return types

### ISSUE THREAD

**Issue by aksatbharat** [tghosgor/postgrespp#6]
I  am not able to  retrieve numeric return values . here is an example function that returns out4 and out5 as numeric. 

CREATE OR REPLACE FUNCTION common.my_function(p1 integer, p2 integer, p3 text, p4 numeric, p5 text)
 RETURNS TABLE(out1 text, out2 text, out3 text, out4 numeric, out5 numeric)
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Do some processing here
    -- ...

    -- Return the output values
    RETURN QUERY 
        SELECT 
            'output1' AS out1, 
            'output2' AS out2, 
            'output3' AS out3, 
            123.45 AS out4, 
            678.90 AS out5;
END;
$function$
;
in result.hpp I have added 
PGresult* underlying_result_handle() { return res_;}

Here is test code cpp  code, 
std::string query = fmt::format("select out1 \"o1\", out2 \"o2\",out3 \"o3\", out4 \"o4\" ,out5 \"o5\"  from common.my_function ({}, {}, '{}', {}, '{}')",
                                                        fmt::arg("p1", 1),
                                                        fmt::arg("p2", 1),
                                                        fmt::arg("p3", "Delete"),
                                                        fmt::arg("p4", 1),
                                                        fmt::arg("p5", "USD"));

                        auto result_future = async_exec(*_dbconn,
                                                        query,
                                                        postgrespp::use_future);

                        postgrespp::result result = result_future.get();
                        if (result.ok()) {

                            auto result_handle = result.underlying_result_handle();
                            std::cout << "Rows=" << PQntuples(result_handle) << std::endl;
                            std::string o1,o2, o3;
                            double o4, o5;
                          std::cout << std::atof(PQgetvalue(result_handle, 0, 3)) << std::endl; ///always prints 0

                   }

**Comment by tghosgor** [comment]
That would probably happen because we're using "binary protocol" and returned value is not a string representation of the value.

**Comment by tghosgor** [comment]
See here about how that is encoded -> https://stackoverflow.com/questions/72788883/how-to-handle-a-numeric-data-type-from-postgresql-in-c.

What you could do easiest is to cast the values to text to get them as string:

`select out1 "o1", out2 "o2",out3 "o3", out4::text "o4" ,out5::text "o5"`

**Comment by tghosgor** [comment]
Alternatively, you can use floating-point types (`real` or `double precision`) columns and define a decoder.

```
template <class T>
class type_decoder<T, std::enable_if_t<std::is_floating_point_v<T>>> {
public:
  static constexpr std::size_t min_size = sizeof(T);
  static constexpr std::size_t max_size = sizeof(T);
  static constexpr bool nullable = false;

public:
  T from_binary(const char* data, std::size_t length) {
    using namespace boost::endian;

    return endian_load<T, sizeof(T), order::big>(reinterpret_cast<unsigned const char*>(data));
  }
};
```

I'll add this to builtin decoders and release a new version.
